# Generated by Django 4.2.16 on 2025-03-27 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2025, 3, 27, 7, 29, 17, 162056))),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='pub_date',
            field=models.ManyToManyField(to='testApp.pubdate'),
        ),
    ]
