# Generated by Django 4.2.16 on 2025-03-27 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_pubdate_books_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubdate',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
