# Generated by Django 4.2.16 on 2025-04-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0004_restaurant_sale_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="open_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
