# Generated by Django 4.2.16 on 2025-05-02 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0005_restaurant_open_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn_no", models.CharField(max_length=255)),
                ("no_of_pages", models.IntegerField()),
                ("language", models.CharField(max_length=100)),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="testApp.books"
                    ),
                ),
            ],
        ),
    ]
