# Generated by Django 4.2.16 on 2025-07-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0006_bookdetails"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="restaurant",
        ),
        migrations.AlterField(
            model_name="books",
            name="pub_date",
            field=models.ManyToManyField(related_name="tracks", to="testApp.pubdate"),
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
        migrations.DeleteModel(
            name="Restaurant",
        ),
        migrations.DeleteModel(
            name="Sale",
        ),
    ]
